### PR TITLE
Modified dashboard page and added style to it

### PR DESCRIPTION
**Pull request by ImeneImene15**
I am still working on the dark theme idea , I have a slight problem that I'll figure it out. 
The logo is not the app's original logo, I just took it from google so I can calculate how much space it will take (for test).
And finally, the chart is just an idea, I had another one called polarArea, but it depends on which kind of data we are using in the chart.

### CODE REVIEW

**Comment by ZairiAimenDz** [comment]
just a minute to check

**Comment by ZairiAimenDz** [comment]
that was some amazing work ngl.
Though I'm not going to merge it now for the following reasons, and btw take your time, dashboard is something that must be done slowly but surely.as long as we don't have a set deadline we are good:

- Replace all static links with {{ asset('relative path in public folder') }}
- In Dashboard Layout we only want the menus and not the whole page so you can put the insides ( ) into another page (**Views/Dashboard/Index.blade.php** maybe) move these elements to another page that extends the layout :
image 
- Everything else is well done just hope you would divide the css file of the dashboard on the scss files if you could ( use a scss watcher to compile them to css like i did ), this isn't necessary i will do it eventually when necessary it's just so we could have only one css file.

Good Work And Good Luck.

**Comment by ZairiAimenDz** [comment]
I Also forgot to tell you not to forget about using routes and controllers when continuing the work

**Comment by ImeneImene15** [comment]
Got it, I will fix these issues. Thank you.

**Comment by ImeneImene15** [comment]
So, I added a few options and for the things you told me to fix I did not forget them, I just had trouble with the links a bit but I will fix them.

**Pull request merged**
