### PR TITLE
login page

### PR DESCRIPTION
**Pull request by NadjetBoumezoued**

### CODE REVIEW

**Comment by ZairiAimenDz** [comment]
just a minute i check these

**Comment by ZairiAimenDz** [comment]
Good work. I liked that you used controllers to clean the code up a bit.
But I'm not going to merge it for the following reasons :
- the files should be divided into folders ( just for clean code )
- For the login don't use any side bar and have it centered : use .hero class on the outside div
- we need colors xd, so don't overdo it with the bg-gray.
but no worries we still have time i think, so don't rush anything.
I will be merging this once these are fixed.

good luck

**Comment by ZairiAimenDz** [comment]
Also use a scss watcher extension to compile scss to css, and once you finish divide the new css classes in login.css to it's related .scss file.

**Comment by NadjetBoumezoued** [comment]
Okey thank you ,i will fix it

Le lun. 10 janv. 2022 à 07:39, Aimen Zairi ***@***.***> a
écrit :

**Pull request merged**
